from ast import Return
from re import M

m = 20
print (m)
def esoo (y, x):
    return y+x 

resultado = esoo (45, 5)
print (resultado)

def sumar (e,f):
    return e+f
resultado = sumar (566,766)
print (resultado)


# Tipo funcion
def mi_suma (e,f):
    resultado = e+f
    print (resultado)
#valores
num1= 7856646
num2= 678576
#resultado
res = mi_suma (num1,num2)
print= (resultado)



suma = input('ingrese un numero')
def suma (x,y):
    res = x+y
    print (res)

if suma == '1':
    a = int (input ())
    b = int (input ())

    res = suma (a,b)
    print (res)




